version: "3.8"

services:
  ocr-api:
    build: .
    container_name: ocr
    restart: always
    ports:
      - "6632:6632"
    volumes:
      - ./:/app # 开发模式下挂载代码目录，便于修改
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=localhost,127.0.0.1,你的NAS的IP地址
    command: gunicorn --bind 0.0.0.0:6632 ocr.wsgi:application
